from __future__ import annotations

import json
import shutil
import subprocess
import zipfile
from pathlib import Path

import pytest
import yaml

from genpy_llm.python_corpus_collector import (
    collect_python_corpus,
    load_corpus_collector_config,
    run_corpus_collector_cli,
)


def test_local_collection_validates_filters_and_preserves_structure(tmp_path: Path) -> None:
    source = tmp_path / "source"
    (source / "pkg").mkdir(parents=True)
    (source / "pkg" / "main.py").write_text(
        "def add(left: int, right: int) -> int:\n    return left + right\n",
        encoding="utf-8",
    )
    (source / "broken.py").write_text("def broken(:\n", encoding="utf-8")
    (source / "invalid_utf8.py").write_bytes(b"value = '\xff'\n")
    (source / "tiny.py").write_text("x=1\n", encoding="utf-8")
    (source / "large.py").write_text("#" * 300 + "\nx = 1\n", encoding="utf-8")
    (source / "service_pb2.py").write_text("value = 1\n", encoding="utf-8")
    (source / "codegen.py").write_text(
        "# This file is automatically generated. Do not edit.\nvalue = 1\n",
        encoding="utf-8",
    )
    (source / ".venv").mkdir()
    (source / ".venv" / "ignored.py").write_text("def broken(:\n", encoding="utf-8")
    (source / "build").mkdir()
    (source / "build" / "ignored.py").write_text("def broken(:\n", encoding="utf-8")
    config = _config(
        tmp_path,
        [{"id": "library", "type": "local", "location": "source", "license": "MIT"}],
        minimum=5,
        maximum=200,
    )

    first = collect_python_corpus(config)

    assert first.files_scanned == 7
    assert first.files_accepted == 1
    assert first.files_rejected == 6
    assert first.rejection_reasons == {
        "generated_file": 2,
        "invalid_python_syntax": 1,
        "invalid_utf8": 1,
        "too_large": 1,
        "too_small": 1,
    }
    assert (tmp_path / "raw" / "library" / "pkg" / "main.py").is_file()
    provenance = _manifest(config.provenance_manifest)
    assert provenance[0]["source"]["id"] == "library"
    assert provenance[0]["source_path"] == "pkg/main.py"
    assert provenance[0]["stored_path"] == "library/pkg/main.py"
    assert provenance[0]["license"] == "MIT"
    assert provenance[0]["collection_timestamp"]

    second = collect_python_corpus(config)

    assert second.files_accepted == 0
    assert second.files_unchanged == 1
    assert len(_manifest(config.provenance_manifest)) == 1


def test_individual_files_are_deduplicated_by_content(tmp_path: Path) -> None:
    content = "def identity(value):\n    return value\n"
    (tmp_path / "one.py").write_text(content, encoding="utf-8")
    (tmp_path / "two.py").write_text(content, encoding="utf-8")
    config = _config(
        tmp_path,
        [
            {"id": "one", "type": "file", "location": "one.py", "license": "BSD-3-Clause"},
            {"id": "two", "type": "file", "location": "two.py", "license": "BSD-3-Clause"},
        ],
    )

    result = collect_python_corpus(config)

    assert result.files_scanned == 2
    assert result.files_accepted == 1
    assert result.files_rejected == 1
    assert result.rejection_reasons == {"duplicate_content": 1}
    assert (tmp_path / "raw" / "one" / "one.py").is_file()
    assert not (tmp_path / "raw" / "two" / "two.py").exists()


def test_zip_collection_is_safe_and_preserves_archive_paths(tmp_path: Path) -> None:
    archive = tmp_path / "source.zip"
    with zipfile.ZipFile(archive, "w") as output:
        output.writestr("package/nested/module.py", "def answer():\n    return 42\n")
        output.writestr("package/broken.py", "def broken(:\n")
        output.writestr("package/client_generated.py", "value = 1\n")
        output.writestr("package/__pycache__/ignored.py", "def broken(:\n")
        output.writestr("../escape.py", "value = 1\n")
    config = _config(
        tmp_path,
        [{"id": "archive", "type": "zip", "location": "source.zip", "license": None}],
    )

    result = collect_python_corpus(config)

    assert result.files_scanned == 4
    assert result.files_accepted == 1
    assert result.files_rejected == 3
    assert result.rejection_reasons == {
        "generated_file": 1,
        "invalid_python_syntax": 1,
        "unsafe_archive_path": 1,
    }
    assert (tmp_path / "raw" / "archive" / "package" / "nested" / "module.py").is_file()
    assert not (tmp_path / "escape.py").exists()


@pytest.mark.skipif(shutil.which("git") is None, reason="git is not installed")
def test_local_git_repository_records_exact_revision(tmp_path: Path) -> None:
    repository = tmp_path / "repository"
    repository.mkdir()
    (repository / "src").mkdir()
    (repository / "src" / "module.py").write_text(
        "class Example:\n    pass\n",
        encoding="utf-8",
    )
    (repository / "dist").mkdir()
    (repository / "dist" / "ignored.py").write_text("value = 1\n", encoding="utf-8")
    _git(repository, "init", "--quiet")
    _git(repository, "config", "user.email", "collector@example.invalid")
    _git(repository, "config", "user.name", "Collector Test")
    _git(repository, "add", ".")
    _git(repository, "commit", "--quiet", "-m", "fixture")
    revision = _git(repository, "rev-parse", "HEAD").stdout.strip()
    config = _config(
        tmp_path,
        [{"id": "repo", "type": "git", "location": "repository", "license": "Apache-2.0"}],
    )

    result = collect_python_corpus(config)

    assert result.files_accepted == 1
    provenance = _manifest(config.provenance_manifest)[0]
    assert provenance["source"]["type"] == "git"
    assert provenance["source"]["revision"] == revision
    assert provenance["source_path"] == "src/module.py"


def test_files_placed_directly_in_raw_are_registered_incrementally(tmp_path: Path) -> None:
    config = _config(tmp_path, [])
    direct = config.output_directory / "approved" / "manual.py"
    direct.parent.mkdir(parents=True)
    direct.write_text("def manual():\n    return True\n", encoding="utf-8")

    first = collect_python_corpus(config)
    second = collect_python_corpus(config)

    assert first.files_accepted == 1
    assert second.files_accepted == 0
    assert second.files_unchanged == 1
    provenance = _manifest(config.provenance_manifest)[0]
    assert provenance["source"]["id"] == "manual_raw"
    assert provenance["stored_path"] == "approved/manual.py"


def test_collector_cli_writes_json_report(tmp_path: Path) -> None:
    config = _config(tmp_path, [])

    exit_code = run_corpus_collector_cli(["--config", str(config.config_path)])

    assert exit_code == 0
    report = json.loads(config.report_path.read_text(encoding="utf-8"))
    assert report["files_scanned"] == 0
    assert report["files_accepted"] == 0
    assert report["files_rejected"] == 0


@pytest.mark.skipif(shutil.which("git") is None, reason="git is not installed")
def test_automatic_imports_discovers_local_and_git_repositories(tmp_path: Path) -> None:
    imports = tmp_path / "imports"
    local_repository = imports / "Plain Repository"
    (local_repository / "package").mkdir(parents=True)
    (local_repository / "package" / "local_module.py").write_text(
        "def local_value():\n    return 1\n",
        encoding="utf-8",
    )
    (local_repository / ".genpy-corpus.yaml").write_text(
        "license: MIT\napproval: Reviewed local fixture\n",
        encoding="utf-8",
    )

    git_repository = imports / "git-repository"
    git_repository.mkdir()
    (git_repository / "git_module.py").write_text(
        "class GitValue:\n    pass\n",
        encoding="utf-8",
    )
    (git_repository / ".genpy-corpus.yaml").write_text(
        "license: Apache-2.0\n",
        encoding="utf-8",
    )
    _git(git_repository, "init", "--quiet")
    _git(git_repository, "config", "user.email", "imports@example.invalid")
    _git(git_repository, "config", "user.name", "Imports Test")
    _git(git_repository, "add", ".")
    _git(git_repository, "commit", "--quiet", "-m", "fixture")
    revision = _git(git_repository, "rev-parse", "HEAD").stdout.strip()

    config = _config(tmp_path, [], automatic_imports=True)

    assert {source.source_id for source in config.sources} == {
        "import-git-repository",
        "import-plain-repository",
    }
    assert all(source.discovered_automatically for source in config.sources)

    result = collect_python_corpus(config)

    assert result.files_scanned == 2
    assert result.files_accepted == 2
    provenance = {
        record["source"]["id"]: record
        for record in _manifest(config.provenance_manifest)
    }
    assert provenance["import-plain-repository"]["license"] == "MIT"
    assert provenance["import-plain-repository"]["source"]["approval"] == (
        "Reviewed local fixture"
    )
    assert provenance["import-plain-repository"]["source"][
        "discovered_automatically"
    ] is True
    assert provenance["import-git-repository"]["license"] == "Apache-2.0"
    assert provenance["import-git-repository"]["source"]["type"] == "git"
    assert provenance["import-git-repository"]["source"]["revision"] == revision
    assert (
        tmp_path
        / "raw"
        / "import-plain-repository"
        / "package"
        / "local_module.py"
    ).is_file()

    report = json.loads(config.report_path.read_text(encoding="utf-8"))
    assert report["automatic_imports"]["discovered_source_count"] == 2
    assert report["automatic_imports"]["discovered_sources"] == [
        "import-git-repository",
        "import-plain-repository",
    ]

    second = collect_python_corpus(load_corpus_collector_config(config.config_path))
    assert second.files_accepted == 0
    assert second.files_unchanged == 2


def _config(
    root: Path,
    sources: list[dict[str, object]],
    *,
    minimum: int = 1,
    maximum: int = 10_000,
    automatic_imports: bool = False,
):
    config_path = root / "dataset_pipeline.yaml"
    payload = {
        "version": 1,
        "project_root": ".",
        "corpus_collection": {
            "output_directory": "raw",
            "provenance_manifest": "raw/collection_manifest.jsonl",
            "report": "raw/collection_report.json",
            "log_file": "logs/corpus.log",
            "minimum_file_bytes": minimum,
            "maximum_file_bytes": maximum,
            "git_timeout_seconds": 30,
            "sources": sources,
        },
        "logging": {"level": "INFO"},
    }
    if automatic_imports:
        payload["corpus_collection"]["automatic_imports"] = {
            "enabled": True,
            "directory": "imports",
            "approval": "Approved by test import-directory placement",
            "default_license": None,
        }
    config_path.write_text(yaml.safe_dump(payload, sort_keys=False), encoding="utf-8")
    return load_corpus_collector_config(config_path)


def _manifest(path: Path) -> list[dict[str, object]]:
    return [json.loads(line) for line in path.read_text(encoding="utf-8").splitlines() if line]


def _git(repository: Path, *arguments: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        ["git", "-C", str(repository), *arguments],
        check=True,
        capture_output=True,
        text=True,
    )
