"""Local documentation corpus builder for GenPy continued pretraining."""

from __future__ import annotations

import argparse
import hashlib
import html
import json
import os
import re
import shutil
from collections import Counter
from dataclasses import dataclass, field
from datetime import datetime, timezone
from html.parser import HTMLParser
from pathlib import Path, PurePosixPath
from typing import Any

import yaml

from genpy_llm.code_tokenizer import CodeTokenizer, tokenizer_file_hash
from genpy_llm.sequence_packer import (
    SequencePacker,
    SequencePackingConfig,
    prepare_document_tokens,
)
from genpy_llm.shard_builder import (
    SequenceShardWriter,
    prepare_sequence_output,
    write_sequence_shard_index,
)

UTC = timezone.utc

DEFAULT_CONFIG_PATH = Path("configs/documentation_corpus.yaml")
DEFAULT_ALLOWED_EXTENSIONS = (".md", ".rst", ".html", ".txt")
DEFAULT_SOURCE_DIRECTORIES = ("docs", "peps", "tutorials")
DEFAULT_IGNORED_DIRECTORIES = (
    ".git",
    ".github",
    "__pycache__",
    "node_modules",
    "venv",
    ".venv",
    "env",
    "ENV",
    "build",
    "dist",
    "_build",
    "site",
)
DEFAULT_IGNORED_SUFFIXES = (
    ".png",
    ".jpg",
    ".jpeg",
    ".gif",
    ".pdf",
    ".zip",
    ".exe",
    ".dll",
    ".so",
    ".bin",
)
NAVIGATION_LINE_PATTERNS = (
    re.compile(r"^\s*(previous|next|back to top|edit this page|view source)\s*$", re.I),
    re.compile(r"^\s*(table of contents|contents|on this page|breadcrumb[s]?)\s*$", re.I),
    re.compile(r"^\s*(copyright|©|\(c\))", re.I),
    re.compile(r"^\s*\[[^\]]+\]\((?:#|javascript:|/)?\)\s*$", re.I),
)
AUTOGENERATED_LINK_PATTERN = re.compile(
    r"^\s*[-*]?\s*(previous|next|index|module index|search page|genindex|py-modindex)\b",
    re.I,
)


class DocumentationCorpusError(RuntimeError):
    """Raised when documentation corpus building cannot continue."""


@dataclass(frozen=True)
class DocumentationPackingConfig:
    """Packed-shard generation settings for documentation."""

    context_length: int = 1024
    max_tokens_per_shard: int = 10_000_000
    shard_prefix: str = "documentation"
    add_bos: bool = False
    add_eos: bool = True
    document_boundary: str = "eos"
    pad_final_sequence: bool = False


@dataclass(frozen=True)
class DocumentationCorpusConfig:
    """Validated local documentation corpus configuration."""

    project_root: Path
    corpus_root: Path
    source_directories: tuple[Path, ...]
    tokenizer_path: Path
    min_file_size: int = 80
    max_file_size: int = 2_000_000
    allowed_extensions: tuple[str, ...] = DEFAULT_ALLOWED_EXTENSIONS
    ignored_directories: tuple[str, ...] = DEFAULT_IGNORED_DIRECTORIES
    ignored_suffixes: tuple[str, ...] = DEFAULT_IGNORED_SUFFIXES
    deduplication: bool = True
    packing: DocumentationPackingConfig = field(default_factory=DocumentationPackingConfig)

    @property
    def cleaned_directory(self) -> Path:
        return self.corpus_root / "cleaned_docs"

    @property
    def packed_directory(self) -> Path:
        return self.corpus_root / "packed_docs"

    @property
    def metadata_directory(self) -> Path:
        return self.corpus_root / "metadata"

    @property
    def statistics_directory(self) -> Path:
        return self.corpus_root / "statistics"


@dataclass(frozen=True)
class DocumentationSource:
    """One documentation source file discovered under the configured corpus root."""

    path: Path
    relative_path: PurePosixPath
    source_section: str
    extension: str


@dataclass(frozen=True)
class DocumentationDocument:
    """One cleaned documentation document."""

    source_path: Path
    relative_path: PurePosixPath
    cleaned_path: Path
    source_section: str
    extension: str
    text: str
    character_count: int
    token_ids: tuple[int, ...]
    raw_sha256: str
    normalized_sha256: str


@dataclass(frozen=True)
class DocumentationRejection:
    """One skipped documentation file."""

    path: Path
    relative_path: str
    reason: str
    size_bytes: int = 0


@dataclass(frozen=True)
class DocumentationCorpusResult:
    """Build result and artifact locations."""

    files_processed: int
    files_skipped: int
    duplicates_removed: int
    total_characters: int
    total_tokens: int
    statistics_path: Path
    manifest_path: Path
    shard_index_path: Path


def load_documentation_corpus_config(
    path: Path | str = DEFAULT_CONFIG_PATH,
) -> DocumentationCorpusConfig:
    """Load documentation corpus YAML configuration."""

    config_path = Path(path)
    default_project_root = (
        config_path.resolve().parents[1]
        if config_path.parent.name == "configs"
        else Path.cwd()
    )
    payload = yaml.safe_load(config_path.read_text(encoding="utf-8")) or {}
    if not isinstance(payload, dict):
        raise DocumentationCorpusError("Documentation corpus config must be a YAML mapping.")
    section = _mapping(payload.get("documentation_corpus", payload), "documentation_corpus")
    if "project_root" in payload:
        root = _resolve(config_path.parent.resolve(), Path(payload["project_root"]))
    else:
        root = default_project_root.resolve()
    corpus_root = _resolve(root, Path(section.get("corpus_root", "python_corpus")))
    source_directories = tuple(
        _resolve(corpus_root, Path(value))
        for value in _strings(
            section.get("source_directories", DEFAULT_SOURCE_DIRECTORIES),
            "source_directories",
        )
    )
    packing = _mapping(section.get("packing", {}), "documentation_corpus.packing")
    return DocumentationCorpusConfig(
        project_root=root,
        corpus_root=corpus_root,
        source_directories=source_directories,
        tokenizer_path=_resolve(
            root,
            Path(section.get("tokenizer", "data/tokenizer/tokenizer.json")),
        ),
        min_file_size=_non_negative_int(section.get("min_file_size", 80), "min_file_size"),
        max_file_size=_positive_int(section.get("max_file_size", 2_000_000), "max_file_size"),
        allowed_extensions=_extensions(
            section.get("allowed_extensions", DEFAULT_ALLOWED_EXTENSIONS)
        ),
        ignored_directories=_strings(
            section.get("ignored_directories", DEFAULT_IGNORED_DIRECTORIES),
            "ignored_directories",
        ),
        ignored_suffixes=_extensions(section.get("ignored_suffixes", DEFAULT_IGNORED_SUFFIXES)),
        deduplication=bool(section.get("deduplication", True)),
        packing=DocumentationPackingConfig(
            context_length=_positive_int(packing.get("context_length", 1024), "context_length"),
            max_tokens_per_shard=_positive_int(
                packing.get("max_tokens_per_shard", 10_000_000),
                "max_tokens_per_shard",
            ),
            shard_prefix=_filename(packing.get("shard_prefix", "documentation")),
            add_bos=bool(packing.get("add_bos", False)),
            add_eos=bool(packing.get("add_eos", True)),
            document_boundary=str(packing.get("document_boundary", "eos")),
            pad_final_sequence=bool(packing.get("pad_final_sequence", False)),
        ),
    )


def ensure_documentation_folders(config: DocumentationCorpusConfig) -> None:
    """Create expected documentation input and output folders."""

    for directory in (
        config.corpus_root,
        config.corpus_root / "docs",
        config.corpus_root / "peps",
        config.corpus_root / "tutorials",
        config.cleaned_directory,
        config.packed_directory,
        config.metadata_directory,
        config.statistics_directory,
    ):
        directory.mkdir(parents=True, exist_ok=True)


def scan_documentation_sources(config: DocumentationCorpusConfig) -> list[DocumentationSource]:
    """Recursively scan documentation source directories."""

    ignored_dirs = set(config.ignored_directories)
    ignored_suffixes = set(config.ignored_suffixes)
    allowed_extensions = set(config.allowed_extensions)
    sources: list[DocumentationSource] = []
    for source_directory in config.source_directories:
        if not source_directory.exists():
            continue
        for root, dirnames, filenames in os.walk(source_directory):
            dirnames[:] = sorted(name for name in dirnames if name not in ignored_dirs)
            current = Path(root)
            for filename in sorted(filenames):
                path = current / filename
                suffix = path.suffix.lower()
                if suffix not in allowed_extensions or suffix in ignored_suffixes:
                    continue
                relative = PurePosixPath(path.relative_to(config.corpus_root).as_posix())
                if any(part in ignored_dirs for part in relative.parts):
                    continue
                sources.append(
                    DocumentationSource(
                        path=path,
                        relative_path=relative,
                        source_section=relative.parts[0] if relative.parts else "",
                        extension=suffix,
                    )
                )
    return sources


def process_documentation(
    sources: list[DocumentationSource],
    config: DocumentationCorpusConfig,
    tokenizer: CodeTokenizer,
) -> tuple[list[DocumentationDocument], list[DocumentationRejection]]:
    """Clean, deduplicate, tokenize, and write documentation files."""

    documents: list[DocumentationDocument] = []
    rejected: list[DocumentationRejection] = []
    seen_hashes: set[str] = set()
    config.cleaned_directory.mkdir(parents=True, exist_ok=True)
    for source in sources:
        size = source.path.stat().st_size
        if size == 0:
            rejected.append(_reject(source, "empty_file", size))
            continue
        if size < config.min_file_size:
            rejected.append(_reject(source, "too_small", size))
            continue
        if size > config.max_file_size:
            rejected.append(_reject(source, "too_large", size))
            continue
        try:
            raw_text = source.path.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            rejected.append(_reject(source, "invalid_utf8", size))
            continue
        cleaned = clean_documentation_text(raw_text, source.extension)
        if not cleaned.strip():
            rejected.append(_reject(source, "empty_after_cleaning", size))
            continue
        normalized_sha = hashlib.sha256(cleaned.encode("utf-8")).hexdigest()
        if config.deduplication and normalized_sha in seen_hashes:
            rejected.append(_reject(source, "duplicate", size))
            continue
        seen_hashes.add(normalized_sha)
        cleaned_path = _cleaned_path(config, source.relative_path)
        cleaned_path.parent.mkdir(parents=True, exist_ok=True)
        cleaned_path.write_text(cleaned, encoding="utf-8")
        documents.append(
            DocumentationDocument(
                source_path=source.path,
                relative_path=source.relative_path,
                cleaned_path=cleaned_path,
                source_section=source.source_section,
                extension=source.extension,
                text=cleaned,
                character_count=len(cleaned),
                token_ids=tuple(tokenizer.encode(cleaned)),
                raw_sha256=hashlib.sha256(raw_text.encode("utf-8")).hexdigest(),
                normalized_sha256=normalized_sha,
            )
        )
    return documents, rejected


def clean_documentation_text(text: str, extension: str) -> str:
    """Clean one documentation file while preserving educational content."""

    if extension == ".html":
        text = _DocumentationHTMLExtractor().extract(text)
    text = html.unescape(text)
    text = _remove_fenced_toc_blocks(text)
    kept: list[str] = []
    in_code = False
    for raw_line in _normalize_newlines(text).split("\n"):
        stripped = raw_line.strip()
        if stripped.startswith("```"):
            in_code = not in_code
            kept.append(stripped)
            continue
        if in_code or raw_line.startswith(("    ", "\t")):
            kept.append(raw_line.rstrip())
            continue
        line = _clean_line(raw_line)
        if _is_meaningful_line(line):
            kept.append(line)
    return _collapse_whitespace("\n".join(kept))


def write_documentation_metadata(
    documents: list[DocumentationDocument],
    rejected: list[DocumentationRejection],
    config: DocumentationCorpusConfig,
) -> Path:
    """Write accepted and rejected documentation metadata."""

    config.metadata_directory.mkdir(parents=True, exist_ok=True)
    manifest = config.metadata_directory / "documentation_manifest.jsonl"
    with manifest.open("w", encoding="utf-8") as file:
        for document in documents:
            file.write(json.dumps(_document_record(document), sort_keys=True) + "\n")
    rejected_path = config.metadata_directory / "documentation_rejected.jsonl"
    with rejected_path.open("w", encoding="utf-8") as file:
        for item in rejected:
            file.write(json.dumps(_rejection_record(item), sort_keys=True) + "\n")
    return manifest


def pack_documentation(
    documents: list[DocumentationDocument],
    tokenizer: CodeTokenizer,
    config: DocumentationCorpusConfig,
    manifest_path: Path,
    *,
    force: bool = False,
) -> Path:
    """Pack documentation into train-ready fixed-length uint16 shards."""

    index_path = config.packed_directory / "index.json"
    if force:
        prepare_sequence_output(
            config.packed_directory,
            config.packing.shard_prefix,
            [index_path],
        )
    config.packed_directory.mkdir(parents=True, exist_ok=True)
    if not documents:
        write_sequence_shard_index(
            index_path,
            SequenceShardWriter(
                config.packed_directory,
                max_tokens_per_shard=config.packing.max_tokens_per_shard,
                context_length=config.packing.context_length,
                prefix=config.packing.shard_prefix,
            ).close(),
            tokenizer_path=config.tokenizer_path,
            tokenizer_sha256=tokenizer_file_hash(config.tokenizer_path),
            vocab_size=tokenizer.vocab_size,
            bos_token_id=tokenizer.bos_token_id,
            eos_token_id=tokenizer.eos_token_id,
            pad_token_id=tokenizer.pad_token_id,
            context_length=config.packing.context_length,
            source_manifest=manifest_path,
            creation_timestamp=datetime.now(UTC).isoformat(),
            build_fingerprint=_build_fingerprint(documents, config),
        )
        return index_path
    packing_config = SequencePackingConfig(
        context_length=config.packing.context_length,
        add_bos=config.packing.add_bos,
        add_eos=config.packing.add_eos,
        document_boundary=config.packing.document_boundary,
        pad_final_sequence=config.packing.pad_final_sequence,
    )
    packer = SequencePacker(packing_config, tokenizer.pad_token_id)
    writer = SequenceShardWriter(
        config.packed_directory,
        max_tokens_per_shard=config.packing.max_tokens_per_shard,
        context_length=config.packing.context_length,
        prefix=config.packing.shard_prefix,
    )
    try:
        for document in documents:
            prepared = prepare_document_tokens(
                list(document.token_ids),
                bos_token_id=tokenizer.bos_token_id,
                eos_token_id=tokenizer.eos_token_id,
                config=packing_config,
            )
            for sequence in packer.add_document(prepared, _document_record(document)):
                writer.write_sequence(sequence)
        for sequence in packer.finish():
            writer.write_sequence(sequence)
        shard_stats = writer.close()
    except Exception:
        writer.abort()
        raise
    write_sequence_shard_index(
        index_path,
        shard_stats,
        tokenizer_path=config.tokenizer_path,
        tokenizer_sha256=tokenizer_file_hash(config.tokenizer_path),
        vocab_size=tokenizer.vocab_size,
        bos_token_id=tokenizer.bos_token_id,
        eos_token_id=tokenizer.eos_token_id,
        pad_token_id=tokenizer.pad_token_id,
        context_length=config.packing.context_length,
        source_manifest=manifest_path,
        creation_timestamp=datetime.now(UTC).isoformat(),
        build_fingerprint=_build_fingerprint(documents, config),
    )
    return index_path


def build_documentation_statistics(
    documents: list[DocumentationDocument],
    rejected: list[DocumentationRejection],
    config: DocumentationCorpusConfig,
    shard_index: dict[str, Any],
) -> dict[str, Any]:
    """Build documentation corpus statistics."""

    total_tokens = sum(len(document.token_ids) for document in documents)
    files_processed = len(documents)
    reasons = Counter(item.reason for item in rejected)
    return {
        "created_at": datetime.now(UTC).isoformat(),
        "files_processed": files_processed,
        "files_skipped": len(rejected),
        "duplicates_removed": reasons.get("duplicate", 0),
        "total_characters": sum(document.character_count for document in documents),
        "total_tokens": total_tokens,
        "average_tokens_per_document": round(total_tokens / files_processed, 6)
        if files_processed
        else 0.0,
        "source_sections": dict(Counter(document.source_section for document in documents)),
        "extensions": dict(Counter(document.extension for document in documents)),
        "skip_reasons": dict(sorted(reasons.items())),
        "tokenizer": str(config.tokenizer_path),
        "tokenizer_sha256": tokenizer_file_hash(config.tokenizer_path),
        "packing": shard_index,
    }


def write_documentation_statistics(
    statistics: dict[str, Any],
    config: DocumentationCorpusConfig,
) -> Path:
    """Write JSON and Markdown statistics reports."""

    config.statistics_directory.mkdir(parents=True, exist_ok=True)
    json_path = config.statistics_directory / "documentation_statistics.json"
    json_path.write_text(json.dumps(statistics, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    markdown_path = config.statistics_directory / "documentation_statistics.md"
    markdown_path.write_text(_statistics_markdown(statistics), encoding="utf-8")
    return json_path


def run_documentation_corpus_pipeline(
    config: DocumentationCorpusConfig,
    *,
    force: bool = False,
) -> DocumentationCorpusResult:
    """Run the full local-only documentation corpus pipeline."""

    ensure_documentation_folders(config)
    if force:
        for directory in (
            config.cleaned_directory,
            config.packed_directory,
            config.metadata_directory,
            config.statistics_directory,
        ):
            if directory.exists():
                shutil.rmtree(directory)
        ensure_documentation_folders(config)
    tokenizer = CodeTokenizer.from_file(config.tokenizer_path)
    sources = scan_documentation_sources(config)
    documents, rejected = process_documentation(sources, config, tokenizer)
    manifest_path = write_documentation_metadata(documents, rejected, config)
    shard_index_path = pack_documentation(
        documents,
        tokenizer,
        config,
        manifest_path,
        force=force,
    )
    shard_index = json.loads(shard_index_path.read_text(encoding="utf-8"))
    statistics = build_documentation_statistics(documents, rejected, config, shard_index)
    statistics_path = write_documentation_statistics(statistics, config)
    return DocumentationCorpusResult(
        files_processed=statistics["files_processed"],
        files_skipped=statistics["files_skipped"],
        duplicates_removed=statistics["duplicates_removed"],
        total_characters=statistics["total_characters"],
        total_tokens=statistics["total_tokens"],
        statistics_path=statistics_path,
        manifest_path=manifest_path,
        shard_index_path=shard_index_path,
    )


def run_documentation_corpus_cli(argv: list[str] | None = None) -> int:
    """CLI entrypoint for documentation corpus building."""

    parser = argparse.ArgumentParser(description="Build a local GenPy documentation corpus.")
    parser.add_argument("--config", type=Path, default=DEFAULT_CONFIG_PATH)
    parser.add_argument("--force", action="store_true")
    args = parser.parse_args(argv)
    result = run_documentation_corpus_pipeline(
        load_documentation_corpus_config(args.config),
        force=args.force,
    )
    print(f"Files processed: {result.files_processed}")
    print(f"Files skipped: {result.files_skipped}")
    print(f"Duplicates removed: {result.duplicates_removed}")
    print(f"Total characters: {result.total_characters}")
    print(f"Total tokens: {result.total_tokens}")
    print(f"Statistics: {result.statistics_path}")
    print(f"Packed index: {result.shard_index_path}")
    return 0


class _DocumentationHTMLExtractor(HTMLParser):
    """Extract meaningful text from HTML documentation."""

    block_tags = {"p", "div", "section", "article", "li", "tr", "table", "pre", "code"}
    heading_tags = {"h1", "h2", "h3", "h4", "h5", "h6"}
    skipped_tags = {"script", "style", "nav", "header", "footer", "noscript", "svg"}
    skipped_attrs = {
        "breadcrumb",
        "breadcrumbs",
        "navbar",
        "navigation",
        "sidebar",
        "toc",
        "toctree",
        "footer",
        "header",
        "copyright",
        "search",
    }

    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self.parts: list[str] = []
        self.skip_depth = 0
        self.pre_depth = 0

    def extract(self, text: str) -> str:
        self.feed(text)
        self.close()
        return "".join(self.parts)

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        tag = tag.lower()
        if self.skip_depth or tag in self.skipped_tags or self._has_skipped_attr(attrs):
            self.skip_depth += 1
            return
        if tag in self.heading_tags:
            level = int(tag[1])
            self.parts.append("\n" + ("#" * level) + " ")
        elif tag in self.block_tags:
            self.parts.append("\n")
        if tag == "pre":
            self.pre_depth += 1
            self.parts.append("```\n")

    def handle_endtag(self, tag: str) -> None:
        tag = tag.lower()
        if self.skip_depth:
            self.skip_depth -= 1
            return
        if tag == "pre" and self.pre_depth:
            self.pre_depth -= 1
            self.parts.append("\n```\n")
        elif tag in self.block_tags or tag in self.heading_tags:
            self.parts.append("\n")

    def handle_data(self, data: str) -> None:
        if self.skip_depth:
            return
        self.parts.append(data if self.pre_depth else data.strip() + " ")

    def _has_skipped_attr(self, attrs: list[tuple[str, str | None]]) -> bool:
        values = " ".join(value or "" for name, value in attrs if name in {"class", "id", "role"})
        lowered = values.lower()
        return any(marker in lowered for marker in self.skipped_attrs)


def _normalize_newlines(text: str) -> str:
    return text.replace("\r\n", "\n").replace("\r", "\n")


def _remove_fenced_toc_blocks(text: str) -> str:
    lines = _normalize_newlines(text).split("\n")
    output: list[str] = []
    in_rst_toc = False
    in_code = False
    for line in lines:
        stripped = line.strip()
        if stripped.startswith("```"):
            in_code = not in_code
            output.append(line)
            continue
        if in_code:
            output.append(line)
            continue
        if stripped.startswith(".. toctree::") or stripped.startswith(".. contents::"):
            in_rst_toc = True
            continue
        if in_rst_toc:
            if stripped and (line.startswith(" ") or line.startswith("\t")):
                continue
            in_rst_toc = False
        output.append(line)
    return "\n".join(output)


def _clean_line(line: str) -> str:
    line = re.sub(r"<[^>]+>", " ", line)
    line = re.sub(r"\s+", " ", line).strip()
    return line


def _is_meaningful_line(line: str) -> bool:
    if not line:
        return True
    if any(pattern.search(line) for pattern in NAVIGATION_LINE_PATTERNS):
        return False
    if AUTOGENERATED_LINK_PATTERN.search(line):
        return False
    return True


def _collapse_whitespace(text: str) -> str:
    lines = [line.rstrip() for line in text.split("\n")]
    collapsed: list[str] = []
    blank = False
    for line in lines:
        if not line.strip():
            if not blank:
                collapsed.append("")
            blank = True
            continue
        collapsed.append(line)
        blank = False
    return "\n".join(collapsed).strip() + "\n"


def _cleaned_path(config: DocumentationCorpusConfig, relative_path: PurePosixPath) -> Path:
    return config.cleaned_directory / relative_path.with_suffix(".txt")


def _reject(
    source: DocumentationSource,
    reason: str,
    size_bytes: int,
) -> DocumentationRejection:
    return DocumentationRejection(
        path=source.path,
        relative_path=source.relative_path.as_posix(),
        reason=reason,
        size_bytes=size_bytes,
    )


def _document_record(document: DocumentationDocument) -> dict[str, Any]:
    return {
        "source_path": str(document.source_path),
        "stored_path": document.relative_path.as_posix(),
        "cleaned_path": str(document.cleaned_path),
        "source_section": document.source_section,
        "source_type": "documentation",
        "source_id": document.source_section,
        "extension": document.extension,
        "character_count": document.character_count,
        "token_count": len(document.token_ids),
        "content_sha256": document.raw_sha256,
        "normalized_sha256": document.normalized_sha256,
    }


def _rejection_record(item: DocumentationRejection) -> dict[str, Any]:
    return {
        "source_path": str(item.path),
        "stored_path": item.relative_path,
        "reason": item.reason,
        "size_bytes": item.size_bytes,
    }


def _statistics_markdown(statistics: dict[str, Any]) -> str:
    return (
        "# Documentation Corpus Statistics\n\n"
        f"- Files processed: {statistics['files_processed']}\n"
        f"- Files skipped: {statistics['files_skipped']}\n"
        f"- Duplicates removed: {statistics['duplicates_removed']}\n"
        f"- Total characters: {statistics['total_characters']}\n"
        f"- Total tokens: {statistics['total_tokens']}\n"
        f"- Average tokens per document: {statistics['average_tokens_per_document']}\n"
    )


def _build_fingerprint(
    documents: list[DocumentationDocument],
    config: DocumentationCorpusConfig,
) -> str:
    digest = hashlib.sha256()
    digest.update(str(config.corpus_root).encode("utf-8"))
    for document in documents:
        digest.update(document.relative_path.as_posix().encode("utf-8"))
        digest.update(document.normalized_sha256.encode("utf-8"))
    return digest.hexdigest()


def _resolve(root: Path, path: Path) -> Path:
    return path if path.is_absolute() else (root / path).resolve()


def _mapping(value: Any, name: str) -> dict[str, Any]:
    if value is None:
        return {}
    if not isinstance(value, dict):
        raise DocumentationCorpusError(f"{name} must be a mapping.")
    return value


def _strings(value: Any, name: str) -> tuple[str, ...]:
    if not isinstance(value, (list, tuple)):
        raise DocumentationCorpusError(f"{name} must be a list.")
    values = tuple(str(item) for item in value if str(item))
    if not values:
        raise DocumentationCorpusError(f"{name} must not be empty.")
    return values


def _extensions(value: Any) -> tuple[str, ...]:
    extensions: list[str] = []
    for item in _strings(value, "extensions"):
        extension = item.lower()
        extensions.append(extension if extension.startswith(".") else f".{extension}")
    return tuple(extensions)


def _positive_int(value: Any, name: str) -> int:
    number = int(value)
    if number <= 0:
        raise DocumentationCorpusError(f"{name} must be greater than zero.")
    return number


def _non_negative_int(value: Any, name: str) -> int:
    number = int(value)
    if number < 0:
        raise DocumentationCorpusError(f"{name} must be non-negative.")
    return number


def _filename(value: Any) -> str:
    text = str(value)
    if not text or Path(text).name != text:
        raise DocumentationCorpusError("shard_prefix must be a filename component.")
    return text


__all__ = [
    "DocumentationCorpusConfig",
    "DocumentationCorpusError",
    "DocumentationCorpusResult",
    "DocumentationDocument",
    "DocumentationPackingConfig",
    "DocumentationRejection",
    "DocumentationSource",
    "build_documentation_statistics",
    "clean_documentation_text",
    "ensure_documentation_folders",
    "load_documentation_corpus_config",
    "pack_documentation",
    "process_documentation",
    "run_documentation_corpus_cli",
    "run_documentation_corpus_pipeline",
    "scan_documentation_sources",
    "write_documentation_metadata",
    "write_documentation_statistics",
]
