"""Incremental collection of approved source material into ``data/raw``."""

from __future__ import annotations

import argparse
import ast
import fnmatch
import hashlib
import json
import logging
import os
import re
import shutil
import stat
import subprocess
import sys
import tempfile
import zipfile
from collections import Counter
from collections.abc import Callable, Iterable, Iterator, Mapping, Sequence
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from pathlib import Path, PurePosixPath
from typing import Any, Optional

import yaml

UTC = timezone.utc

LOGGER = logging.getLogger("genpy_llm.python_corpus_collector")
COLLECTOR_VERSION = 1
SUPPORTED_SOURCE_TYPES = {"local", "git", "github", "pypi", "zip", "file"}
DEFAULT_IGNORED_DIRECTORIES = (
    ".git",
    ".hg",
    ".svn",
    ".tox",
    ".nox",
    ".venv",
    "venv",
    "env",
    "ENV",
    "__pycache__",
    "build",
    "dist",
    "site-packages",
    ".eggs",
    "*.egg-info",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    "generated",
    "autogenerated",
)
DEFAULT_GENERATED_PATTERNS = (
    "*_generated.py",
    "generated_*.py",
    "*_pb2.py",
    "*_pb2_grpc.py",
    "*_ui.py",
    "versioneer.py",
)
DEFAULT_GENERATED_CONTENT_MARKERS = (
    "@generated",
    "auto-generated",
    "autogenerated",
    "automatically generated",
    "generated by",
    "do not edit",
)
DEFAULT_IMPORT_METADATA_FILE = ".genpy-corpus.yaml"
DEFAULT_ALLOWED_EXTENSIONS = (".py",)
TECHNICAL_TEXT_EXTENSIONS = (".md", ".rst", ".txt")


class CorpusCollectionError(RuntimeError):
    """Raised when corpus configuration or source material cannot be processed."""


@dataclass(frozen=True)
class CorpusSource:
    """One approved input source."""

    source_id: str
    source_type: str
    location: str
    license: str | None
    approval: str | None = None
    revision: str | None = None
    include: tuple[str, ...] = ("**/*.py",)
    exclude: tuple[str, ...] = ()
    discovered_automatically: bool = False
    repository_url: str | None = None
    stars: int | None = None
    repository_created_at: str | None = None
    repository_updated_at: str | None = None
    repository_pushed_at: str | None = None
    default_branch: str | None = None
    package_name: str | None = None
    package_version: str | None = None
    release_date: str | None = None
    homepage: str | None = None
    project_url: str | None = None
    author: str | None = None
    summary: str | None = None
    keywords: str | None = None
    source_archive: str | None = None
    download_url: str | None = None
    archive_sha256: str | None = None


@dataclass(frozen=True)
class CorpusCollectorConfig:
    """Validated configuration for raw corpus collection."""

    config_path: Path
    project_root: Path
    output_directory: Path
    provenance_manifest: Path
    report_path: Path
    minimum_file_bytes: int
    maximum_file_bytes: int
    allowed_extensions: tuple[str, ...]
    ignored_directories: tuple[str, ...]
    generated_file_patterns: tuple[str, ...]
    generated_content_markers: tuple[str, ...]
    manual_license: str | None
    git_timeout_seconds: int
    sources: tuple[CorpusSource, ...]
    automatic_imports_directory: Path | None
    automatic_import_source_ids: tuple[str, ...]
    log_file: Path
    log_level: str


@dataclass(frozen=True)
class SourceCandidate:
    """A single discovered source file and its original bytes."""

    source: CorpusSource
    relative_path: PurePosixPath
    content: bytes
    revision: str | None = None
    pre_rejection: str | None = None


@dataclass
class SourceStatistics:
    """Mutable counters for one configured or manual source."""

    files_scanned: int = 0
    files_accepted: int = 0
    files_unchanged: int = 0
    files_rejected: int = 0
    rejection_reasons: Counter[str] = field(default_factory=Counter)


@dataclass(frozen=True)
class CollectionResult:
    """Paths and totals produced by a corpus collection run."""

    output_directory: Path
    provenance_manifest: Path
    report_path: Path
    files_scanned: int
    files_accepted: int
    files_unchanged: int
    files_rejected: int
    rejection_reasons: dict[str, int]


CandidateDuplicateFilter = Callable[[SourceCandidate, str, str], Optional[str]]


def load_corpus_collector_config(
    path: Path | str = "configs/dataset_pipeline.yaml",
) -> CorpusCollectorConfig:
    """Load the ``corpus_collection`` section of dataset pipeline YAML."""

    config_path = Path(path).resolve()
    if not config_path.is_file():
        raise FileNotFoundError(f"Dataset pipeline config not found: {config_path}")
    try:
        raw = yaml.safe_load(config_path.read_text(encoding="utf-8")) or {}
    except yaml.YAMLError as exc:
        raise CorpusCollectionError(f"Invalid YAML in {config_path}: {exc}") from exc
    if not isinstance(raw, dict):
        raise CorpusCollectionError("Dataset pipeline config must be a YAML mapping.")

    root_value = _required_string(raw.get("project_root", "."), "project_root")
    project_root = (config_path.parent / root_value).resolve()
    section = _mapping(raw.get("corpus_collection", {}), "corpus_collection")
    output_directory = _resolve(
        project_root,
        section.get("output_directory", "data/raw"),
    )
    provenance_manifest = _resolve(
        project_root,
        section.get("provenance_manifest", "data/raw/collection_manifest.jsonl"),
    )
    report_path = _resolve(
        project_root,
        section.get("report", "data/raw/collection_report.json"),
    )
    raw_sources = section.get("sources", [])
    if not isinstance(raw_sources, list):
        raise CorpusCollectionError("corpus_collection.sources must be a list.")
    configured_sources = tuple(_load_source(item) for item in raw_sources)
    automatic_imports = _mapping(
        section.get("automatic_imports", {}),
        "corpus_collection.automatic_imports",
    )
    automatic_imports_enabled = bool(automatic_imports.get("enabled", False))
    automatic_imports_directory = (
        _resolve(
            project_root,
            automatic_imports.get("directory", "data/imports"),
        )
        if automatic_imports_enabled
        else None
    )
    discovered_sources = (
        _discover_automatic_import_sources(
            project_root,
            automatic_imports_directory,
            automatic_imports,
            configured_sources,
        )
        if automatic_imports_directory is not None
        else ()
    )
    sources = (*configured_sources, *discovered_sources)
    source_ids = [source.source_id for source in sources]
    if len(source_ids) != len(set(source_ids)):
        raise CorpusCollectionError("Corpus source IDs must be unique.")
    if "manual_raw" in source_ids:
        raise CorpusCollectionError("Corpus source ID 'manual_raw' is reserved.")

    logging_section = _mapping(raw.get("logging", {}), "logging")
    config = CorpusCollectorConfig(
        config_path=config_path,
        project_root=project_root,
        output_directory=output_directory,
        provenance_manifest=provenance_manifest,
        report_path=report_path,
        minimum_file_bytes=int(section.get("minimum_file_bytes", 1)),
        maximum_file_bytes=int(section.get("maximum_file_bytes", 250_000)),
        allowed_extensions=_extension_tuple(
            section.get("allowed_extensions", DEFAULT_ALLOWED_EXTENSIONS),
            "corpus_collection.allowed_extensions",
        ),
        ignored_directories=_string_tuple(
            section.get("ignored_directories", DEFAULT_IGNORED_DIRECTORIES),
            "corpus_collection.ignored_directories",
        ),
        generated_file_patterns=_string_tuple(
            section.get("generated_file_patterns", DEFAULT_GENERATED_PATTERNS),
            "corpus_collection.generated_file_patterns",
        ),
        generated_content_markers=_string_tuple(
            section.get(
                "generated_content_markers",
                DEFAULT_GENERATED_CONTENT_MARKERS,
            ),
            "corpus_collection.generated_content_markers",
        ),
        manual_license=_optional_string(
            section.get("manual_license"),
            "corpus_collection.manual_license",
        ),
        git_timeout_seconds=int(section.get("git_timeout_seconds", 300)),
        sources=sources,
        automatic_imports_directory=automatic_imports_directory,
        automatic_import_source_ids=tuple(
            source.source_id for source in discovered_sources
        ),
        log_file=_resolve(
            project_root,
            section.get("log_file", "logs/python_corpus_collector.log"),
        ),
        log_level=str(logging_section.get("level", "INFO")).upper(),
    )
    _validate_config(config)
    return config


def configure_collector_logging(
    config: CorpusCollectorConfig,
    *,
    level: str | None = None,
) -> None:
    """Configure console and file logging for the collector CLI."""

    selected = (level or config.log_level).upper()
    numeric_level = getattr(logging, selected, None)
    if not isinstance(numeric_level, int):
        raise CorpusCollectionError(f"Unknown logging level: {selected}")
    config.log_file.parent.mkdir(parents=True, exist_ok=True)
    logging.basicConfig(
        level=numeric_level,
        format="%(asctime)s %(levelname)s %(name)s: %(message)s",
        handlers=[
            logging.StreamHandler(),
            logging.FileHandler(config.log_file, encoding="utf-8"),
        ],
        force=True,
    )


def collect_python_corpus(
    config: CorpusCollectorConfig,
    *,
    sources: Sequence[CorpusSource] | None = None,
    collect_manual: bool = True,
    duplicate_filter: CandidateDuplicateFilter | None = None,
) -> CollectionResult:
    """Collect configured sources and approved files placed directly in the raw tree."""

    started_at = _timestamp()
    config.output_directory.mkdir(parents=True, exist_ok=True)
    if config.automatic_imports_directory is not None:
        config.automatic_imports_directory.mkdir(parents=True, exist_ok=True)
    selected_sources = tuple(config.sources if sources is None else sources)
    manifest = _load_current_manifest(config, selected_sources)
    hashes = _manifest_hash_index(manifest)
    statistics: dict[str, SourceStatistics] = {}

    with tempfile.TemporaryDirectory(prefix="genpy-corpus-") as temporary:
        temporary_root = Path(temporary)
        for source in selected_sources:
            source_stats = statistics.setdefault(source.source_id, SourceStatistics())
            LOGGER.info("Scanning %s source %s", source.source_type, source.source_id)
            for candidate in _iter_source_candidates(config, source, temporary_root):
                _process_candidate(
                    config,
                    candidate,
                    manifest,
                    hashes,
                    source_stats,
                    duplicate_filter,
                )

    if collect_manual:
        _collect_manual_raw_files(config, manifest, hashes, statistics)
    _write_manifest(config.provenance_manifest, manifest.values())

    aggregate_reasons: Counter[str] = Counter()
    for source_stats in statistics.values():
        aggregate_reasons.update(source_stats.rejection_reasons)
    scanned = sum(item.files_scanned for item in statistics.values())
    accepted = sum(item.files_accepted for item in statistics.values())
    unchanged = sum(item.files_unchanged for item in statistics.values())
    rejected = sum(item.files_rejected for item in statistics.values())
    report = {
        "collector_version": COLLECTOR_VERSION,
        "started_at": started_at,
        "completed_at": _timestamp(),
        "configuration": str(config.config_path),
        "output_directory": str(config.output_directory),
        "files_scanned": scanned,
        "files_accepted": accepted,
        "files_unchanged": unchanged,
        "files_rejected": rejected,
        "rejection_reasons": dict(sorted(aggregate_reasons.items())),
        "automatic_imports": {
            "enabled": config.automatic_imports_directory is not None,
            "directory": (
                str(config.automatic_imports_directory)
                if config.automatic_imports_directory is not None
                else None
            ),
            "discovered_sources": list(config.automatic_import_source_ids),
            "discovered_source_count": len(config.automatic_import_source_ids),
        },
        "sources": {
            source_id: {
                **asdict(source_stats),
                "rejection_reasons": dict(sorted(source_stats.rejection_reasons.items())),
            }
            for source_id, source_stats in sorted(statistics.items())
        },
    }
    _atomic_json_dump(report, config.report_path)
    LOGGER.info(
        "Corpus collection complete: scanned=%s accepted=%s unchanged=%s rejected=%s",
        scanned,
        accepted,
        unchanged,
        rejected,
    )
    return CollectionResult(
        output_directory=config.output_directory,
        provenance_manifest=config.provenance_manifest,
        report_path=config.report_path,
        files_scanned=scanned,
        files_accepted=accepted,
        files_unchanged=unchanged,
        files_rejected=rejected,
        rejection_reasons=dict(sorted(aggregate_reasons.items())),
    )


def run_corpus_collector_cli(argv: Sequence[str] | None = None) -> int:
    """Run the raw-corpus collector command-line interface."""

    parser = argparse.ArgumentParser(
        description="Collect approved Python material into the GenPy raw corpus."
    )
    parser.add_argument(
        "--config",
        type=Path,
        default=Path("configs/dataset_pipeline.yaml"),
        help="Dataset pipeline YAML containing corpus_collection settings.",
    )
    parser.add_argument("--log-level", choices=["DEBUG", "INFO", "WARNING", "ERROR"])
    args = parser.parse_args(argv)
    try:
        config = load_corpus_collector_config(args.config)
        configure_collector_logging(config, level=args.log_level)
        result = collect_python_corpus(config)
    except Exception as exc:  # noqa: BLE001
        if LOGGER.isEnabledFor(logging.DEBUG):
            LOGGER.exception("Corpus collection failed")
        else:
            print(f"Error: {exc}", file=sys.stderr)
        return 1
    print("Python corpus collection complete")
    print(f"Raw corpus: {result.output_directory}")
    print(f"Provenance: {result.provenance_manifest}")
    print(f"Report: {result.report_path}")
    print(
        f"Scanned={result.files_scanned} accepted={result.files_accepted} "
        f"unchanged={result.files_unchanged} rejected={result.files_rejected}"
    )
    return 0


def _process_candidate(
    config: CorpusCollectorConfig,
    candidate: SourceCandidate,
    manifest: dict[str, dict[str, Any]],
    hashes: dict[str, set[str]],
    statistics: SourceStatistics,
    duplicate_filter: CandidateDuplicateFilter | None = None,
) -> None:
    statistics.files_scanned += 1
    reason, decoded = _validate_candidate(config, candidate)
    if reason is not None:
        _reject(statistics, reason)
        return
    assert decoded is not None

    stored_relative = PurePosixPath(candidate.source.source_id) / candidate.relative_path
    target = _safe_destination(config.output_directory, stored_relative)
    stored_path = stored_relative.as_posix()
    digest = _bytes_hash(candidate.content)
    existing_entry = manifest.get(stored_path)
    if target.is_file() and _file_hash(target) == digest:
        timestamp = _collection_timestamp(existing_entry)
        manifest[stored_path] = _provenance_record(
            candidate,
            stored_path,
            target,
            digest,
            collection_timestamp=timestamp,
        )
        hashes.setdefault(digest, set()).add(stored_path)
        if existing_entry is None:
            statistics.files_accepted += 1
        else:
            statistics.files_unchanged += 1
        return
    if target.exists() and existing_entry is None:
        _reject(statistics, "destination_conflict")
        return

    duplicate_paths = hashes.get(digest, set()) - {stored_path}
    if duplicate_paths:
        _reject(statistics, "duplicate_content")
        return
    if duplicate_filter is not None:
        duplicate_reason = duplicate_filter(candidate, decoded, digest)
        if duplicate_reason is not None:
            _reject(statistics, duplicate_reason)
            return

    old_digest = (
        existing_entry.get("content_sha256") if existing_entry is not None else None
    )
    _atomic_write_bytes(candidate.content, target)
    if isinstance(old_digest, str):
        hashes.get(old_digest, set()).discard(stored_path)
    hashes.setdefault(digest, set()).add(stored_path)
    manifest[stored_path] = _provenance_record(
        candidate,
        stored_path,
        target,
        digest,
        collection_timestamp=_timestamp(),
    )
    statistics.files_accepted += 1


def _collect_manual_raw_files(
    config: CorpusCollectorConfig,
    manifest: dict[str, dict[str, Any]],
    hashes: dict[str, set[str]],
    statistics: dict[str, SourceStatistics],
) -> None:
    manual = CorpusSource(
        source_id="manual_raw",
        source_type="local",
        location=str(config.output_directory),
        license=config.manual_license,
    )
    source_stats = statistics.setdefault(manual.source_id, SourceStatistics())
    for path, relative in _walk_supported_files(config, config.output_directory):
        stored_path = relative.as_posix()
        existing_entry = manifest.get(stored_path)
        existing_source = (
            existing_entry.get("source") if existing_entry is not None else None
        )
        if isinstance(existing_source, dict) and existing_source.get("id") != "manual_raw":
            continue
        candidate = _file_candidate(config, manual, path, relative)
        source_stats.files_scanned += 1
        reason, decoded = _validate_candidate(config, candidate)
        if reason is not None:
            _reject(source_stats, reason)
            continue
        assert decoded is not None
        digest = _bytes_hash(candidate.content)
        if existing_entry is not None and existing_entry.get("content_sha256") == digest:
            manifest[stored_path] = _provenance_record(
                candidate,
                stored_path,
                path,
                digest,
                collection_timestamp=_collection_timestamp(existing_entry),
            )
            source_stats.files_unchanged += 1
            continue
        if hashes.get(digest, set()) - {stored_path}:
            _reject(source_stats, "duplicate_content")
            continue
        hashes.setdefault(digest, set()).add(stored_path)
        manifest[stored_path] = _provenance_record(
            candidate,
            stored_path,
            path,
            digest,
            collection_timestamp=_timestamp(),
        )
        source_stats.files_accepted += 1


def _iter_source_candidates(
    config: CorpusCollectorConfig,
    source: CorpusSource,
    temporary_root: Path,
) -> Iterator[SourceCandidate]:
    if source.source_type == "local":
        root = _resolve(config.project_root, source.location)
        if _is_within(root, config.output_directory):
            raise CorpusCollectionError(
                f"Source {source.source_id!r} points inside the output directory; "
                "place files there directly instead."
            )
        if not root.is_dir():
            raise FileNotFoundError(f"Local corpus directory not found: {root}")
        yield from _directory_candidates(config, source, root)
    elif source.source_type == "file":
        path = _resolve(config.project_root, source.location)
        if _is_within(path, config.output_directory):
            raise CorpusCollectionError(
                f"Source {source.source_id!r} points inside the output directory; "
                "place the file there directly instead."
            )
        if not path.is_file():
            raise FileNotFoundError(f"Python corpus file not found: {path}")
        yield _file_candidate(config, source, path, PurePosixPath(path.name))
    elif source.source_type == "zip":
        path = _resolve(config.project_root, source.location)
        if _is_within(path, config.output_directory):
            raise CorpusCollectionError(
                f"Source {source.source_id!r} points inside the output directory."
            )
        if not path.is_file():
            raise FileNotFoundError(f"Python corpus ZIP archive not found: {path}")
        yield from _zip_candidates(config, source, path)
    elif source.source_type == "git":
        checkout, revision = _clone_git_source(config, source, temporary_root)
        yield from _directory_candidates(config, source, checkout, revision=revision)
    elif source.source_type == "github":
        root = _resolve(config.project_root, source.location)
        if not root.is_dir() or not (root / ".git").is_dir():
            raise FileNotFoundError(f"GitHub corpus checkout not found: {root}")
        yield from _directory_candidates(config, source, root, revision=source.revision)
    elif source.source_type == "pypi":
        root = _resolve(config.project_root, source.location)
        if not root.is_dir():
            raise FileNotFoundError(f"Extracted PyPI source tree not found: {root}")
        yield from _directory_candidates(config, source, root, revision=source.revision)
    else:  # pragma: no cover - guarded by configuration validation
        raise CorpusCollectionError(f"Unsupported source type: {source.source_type}")


def _directory_candidates(
    config: CorpusCollectorConfig,
    source: CorpusSource,
    root: Path,
    *,
    revision: str | None = None,
) -> Iterator[SourceCandidate]:
    for path, relative in _walk_supported_files(config, root):
        if not _source_path_selected(source, relative):
            continue
        yield _file_candidate(config, source, path, relative, revision=revision)


def _file_candidate(
    config: CorpusCollectorConfig,
    source: CorpusSource,
    path: Path,
    relative: PurePosixPath,
    *,
    revision: str | None = None,
) -> SourceCandidate:
    size = path.stat().st_size
    rejection = None
    if not _is_supported_extension(path.name, config.allowed_extensions):
        rejection = "unsupported_extension"
    elif _is_generated(config, relative):
        rejection = "generated_file"
    elif size < config.minimum_file_bytes:
        rejection = "too_small"
    elif size > config.maximum_file_bytes:
        rejection = "too_large"
    return SourceCandidate(
        source=source,
        relative_path=relative,
        content=b"" if rejection is not None else path.read_bytes(),
        revision=revision,
        pre_rejection=rejection,
    )


def _zip_candidates(
    config: CorpusCollectorConfig,
    source: CorpusSource,
    archive_path: Path,
) -> Iterator[SourceCandidate]:
    try:
        archive = zipfile.ZipFile(archive_path)
    except zipfile.BadZipFile as exc:
        raise CorpusCollectionError(f"Invalid ZIP archive {archive_path}: {exc}") from exc
    with archive:
        for member in sorted(archive.infolist(), key=lambda item: item.filename):
            if member.is_dir() or not _is_supported_extension(
                member.filename,
                config.allowed_extensions,
            ):
                continue
            relative = PurePosixPath(member.filename)
            if _unsafe_archive_path(relative):
                yield SourceCandidate(
                    source=source,
                    relative_path=PurePosixPath(Path(member.filename).name or "unsafe.py"),
                    content=b"",
                    pre_rejection="unsafe_archive_path",
                )
                continue
            if _has_ignored_part(config, relative) or not _source_path_selected(
                source, relative
            ):
                continue
            mode = member.external_attr >> 16
            if stat.S_ISLNK(mode):
                yield SourceCandidate(
                    source=source,
                    relative_path=relative,
                    content=b"",
                    pre_rejection="archive_symlink",
                )
                continue
            if member.file_size > config.maximum_file_bytes:
                yield SourceCandidate(
                    source=source,
                    relative_path=relative,
                    content=b"",
                    pre_rejection="too_large",
                )
                continue
            try:
                content = archive.read(member)
            except (OSError, RuntimeError, zipfile.BadZipFile):
                yield SourceCandidate(
                    source=source,
                    relative_path=relative,
                    content=b"",
                    pre_rejection="archive_read_error",
                )
                continue
            yield SourceCandidate(
                source=source,
                relative_path=relative,
                content=content,
                pre_rejection="generated_file" if _is_generated(config, relative) else None,
            )


def _clone_git_source(
    config: CorpusCollectorConfig,
    source: CorpusSource,
    temporary_root: Path,
) -> tuple[Path, str]:
    if shutil.which("git") is None:
        raise CorpusCollectionError("Git is required for corpus sources of type 'git'.")
    destination = temporary_root / source.source_id
    configured_location = Path(source.location).expanduser()
    local_location = (
        configured_location
        if configured_location.is_absolute()
        else config.project_root / configured_location
    )
    if local_location.exists() and _is_within(local_location, config.output_directory):
        raise CorpusCollectionError(
            f"Git source {source.source_id!r} points inside the output directory."
        )
    clone_location = str(local_location.resolve()) if local_location.exists() else source.location
    command = ["git", "clone", "--quiet"]
    if source.revision is None:
        command.extend(["--depth", "1"])
    command.extend([clone_location, str(destination)])
    _run_git(command, config.git_timeout_seconds, source.source_id)
    if source.revision is not None:
        _run_git(
            ["git", "-C", str(destination), "checkout", "--quiet", source.revision],
            config.git_timeout_seconds,
            source.source_id,
        )
    completed = _run_git(
        ["git", "-C", str(destination), "rev-parse", "HEAD"],
        config.git_timeout_seconds,
        source.source_id,
    )
    return destination, completed.stdout.strip()


def _run_git(command: list[str], timeout: int, source_id: str) -> subprocess.CompletedProcess[str]:
    try:
        return subprocess.run(  # noqa: S603
            command,
            check=True,
            capture_output=True,
            text=True,
            timeout=timeout,
        )
    except (subprocess.CalledProcessError, subprocess.TimeoutExpired) as exc:
        details = getattr(exc, "stderr", "") or str(exc)
        raise CorpusCollectionError(
            f"Git operation failed for source {source_id!r}: {details.strip()}"
        ) from exc


def _walk_supported_files(
    config: CorpusCollectorConfig,
    root: Path,
) -> Iterator[tuple[Path, PurePosixPath]]:
    ignored = {name.casefold() for name in config.ignored_directories}
    for directory, directory_names, file_names in os.walk(root, topdown=True):
        directory_names[:] = sorted(
            name
            for name in directory_names
            if not any(fnmatch.fnmatch(name.casefold(), pattern) for pattern in ignored)
            and not (Path(directory) / name).is_symlink()
            and not (
                root.resolve() != config.output_directory.resolve()
                and (Path(directory) / name).resolve()
                == config.output_directory.resolve()
            )
        )
        for file_name in sorted(file_names):
            if not _is_supported_extension(file_name, config.allowed_extensions):
                continue
            path = Path(directory) / file_name
            if path.is_symlink() or not path.is_file():
                continue
            relative = PurePosixPath(path.relative_to(root).as_posix())
            yield path, relative


def _validate_candidate(
    config: CorpusCollectorConfig,
    candidate: SourceCandidate,
) -> tuple[str | None, str | None]:
    if candidate.pre_rejection is not None:
        return candidate.pre_rejection, None
    size = len(candidate.content)
    if size < config.minimum_file_bytes:
        return "too_small", None
    if size > config.maximum_file_bytes:
        return "too_large", None
    try:
        decoded = candidate.content.decode("utf-8-sig")
    except UnicodeDecodeError:
        return "invalid_utf8", None
    header = "\n".join(decoded.splitlines()[:8]).casefold()
    if any(marker.casefold() in header for marker in config.generated_content_markers):
        return "generated_file", None
    if _is_python_path(candidate.relative_path):
        try:
            ast.parse(decoded, filename=candidate.relative_path.as_posix())
        except (SyntaxError, ValueError, TypeError):
            return "invalid_python_syntax", None
    return None, decoded


def _provenance_record(
    candidate: SourceCandidate,
    stored_path: str,
    target: Path,
    digest: str,
    *,
    collection_timestamp: str,
) -> dict[str, Any]:
    metadata = target.stat()
    return {
        "schema_version": COLLECTOR_VERSION,
        "content_sha256": digest,
        "size_bytes": metadata.st_size,
        "mtime_ns": metadata.st_mtime_ns,
        "source": {
            "id": candidate.source.source_id,
            "type": candidate.source.source_type,
            "location": (
                candidate.source.download_url
                if candidate.source.source_type == "pypi"
                else candidate.source.location
            ),
            "revision": candidate.revision,
            "approval": candidate.source.approval,
            "discovered_automatically": candidate.source.discovered_automatically,
            "repository_url": candidate.source.repository_url,
            "stars": candidate.source.stars,
            "repository_created_at": candidate.source.repository_created_at,
            "repository_updated_at": candidate.source.repository_updated_at,
            "repository_pushed_at": candidate.source.repository_pushed_at,
            "default_branch": candidate.source.default_branch,
            "commit_hash": candidate.revision,
            "package": candidate.source.package_name,
            "version": candidate.source.package_version,
            "release_date": candidate.source.release_date,
            "homepage": candidate.source.homepage,
            "project_url": candidate.source.project_url,
            "author": candidate.source.author,
            "summary": candidate.source.summary,
            "keywords": candidate.source.keywords,
            "source_archive": candidate.source.source_archive,
            "download_url": candidate.source.download_url,
            "archive_sha256": candidate.source.archive_sha256,
        },
        "source_path": candidate.relative_path.as_posix(),
        "stored_path": stored_path,
        "content_type": _content_type(candidate.relative_path),
        "language": _content_language(candidate.relative_path),
        "license": candidate.source.license,
        "collection_timestamp": collection_timestamp,
        "last_seen_timestamp": _timestamp(),
    }


def _load_current_manifest(
    config: CorpusCollectorConfig,
    sources: Sequence[CorpusSource] | None = None,
) -> dict[str, dict[str, Any]]:
    if not config.provenance_manifest.is_file():
        return {}
    manifest: dict[str, dict[str, Any]] = {}
    active_source_ids = {source.source_id for source in (sources or config.sources)}
    with config.provenance_manifest.open("r", encoding="utf-8") as file:
        for line_number, line in enumerate(file, start=1):
            if not line.strip():
                continue
            try:
                record = json.loads(line)
            except json.JSONDecodeError as exc:
                raise CorpusCollectionError(
                    f"Invalid provenance JSON in {config.provenance_manifest}:{line_number}: "
                    f"{exc}"
                ) from exc
            if not isinstance(record, dict) or not isinstance(record.get("stored_path"), str):
                raise CorpusCollectionError(
                    f"Invalid provenance record in {config.provenance_manifest}:{line_number}."
                )
            stored_path = str(record["stored_path"])
            try:
                target = _safe_destination(
                    config.output_directory,
                    PurePosixPath(stored_path),
                )
            except CorpusCollectionError:
                continue
            if not target.is_file():
                continue
            metadata = target.stat()
            digest = record.get("content_sha256")
            if (
                record.get("size_bytes") != metadata.st_size
                or record.get("mtime_ns") != metadata.st_mtime_ns
            ):
                actual_digest = _file_hash(target)
                if actual_digest != digest:
                    source = record.get("source")
                    if isinstance(source, dict) and source.get("id") in active_source_ids:
                        record["_content_stale"] = True
                        manifest[stored_path] = record
                    continue
                record["size_bytes"] = metadata.st_size
                record["mtime_ns"] = metadata.st_mtime_ns
            if isinstance(digest, str):
                manifest[stored_path] = record
    return manifest


def _manifest_hash_index(
    manifest: Mapping[str, Mapping[str, Any]],
) -> dict[str, set[str]]:
    result: dict[str, set[str]] = {}
    for stored_path, record in manifest.items():
        if record.get("_content_stale") is True:
            continue
        digest = record.get("content_sha256")
        if isinstance(digest, str):
            result.setdefault(digest, set()).add(stored_path)
    return result


def _collection_timestamp(record: Mapping[str, Any] | None) -> str:
    if record is not None:
        value = record.get("collection_timestamp")
        if isinstance(value, str) and value:
            return value
    return _timestamp()


def _write_manifest(path: Path, records: Iterable[Mapping[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    partial = Path(f"{path}.partial")
    partial.unlink(missing_ok=True)
    try:
        with partial.open("w", encoding="utf-8", newline="\n") as file:
            for record in sorted(records, key=lambda item: str(item["stored_path"])):
                json.dump(record, file, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
                file.write("\n")
        os.replace(partial, path)
    except Exception:
        partial.unlink(missing_ok=True)
        raise


def _atomic_write_bytes(content: bytes, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    partial = Path(f"{path}.partial")
    partial.unlink(missing_ok=True)
    try:
        partial.write_bytes(content)
        os.replace(partial, path)
    except Exception:
        partial.unlink(missing_ok=True)
        raise


def _atomic_json_dump(payload: Mapping[str, Any], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    partial = Path(f"{path}.partial")
    partial.unlink(missing_ok=True)
    try:
        with partial.open("w", encoding="utf-8", newline="\n") as file:
            json.dump(payload, file, ensure_ascii=False, indent=2, sort_keys=True)
            file.write("\n")
        os.replace(partial, path)
    except Exception:
        partial.unlink(missing_ok=True)
        raise


def _load_source(raw: object) -> CorpusSource:
    item = _mapping(raw, "corpus source")
    source_id = _required_string(item.get("id"), "corpus source id")
    if re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9_.-]*", source_id) is None:
        raise CorpusCollectionError(
            f"Corpus source ID {source_id!r} must contain only letters, digits, '.', '_' or '-'."
        )
    source_type = _required_string(item.get("type"), f"{source_id}.type").lower()
    if source_type not in SUPPORTED_SOURCE_TYPES:
        raise CorpusCollectionError(
            f"{source_id}.type must be one of: {', '.join(sorted(SUPPORTED_SOURCE_TYPES))}."
        )
    return CorpusSource(
        source_id=source_id,
        source_type=source_type,
        location=_required_string(item.get("location"), f"{source_id}.location"),
        license=_optional_string(item.get("license"), f"{source_id}.license"),
        approval=_optional_string(item.get("approval"), f"{source_id}.approval"),
        revision=_optional_string(item.get("revision"), f"{source_id}.revision"),
        include=_string_tuple(item.get("include", ["**/*.py"]), f"{source_id}.include"),
        exclude=_string_tuple(item.get("exclude", []), f"{source_id}.exclude"),
        discovered_automatically=bool(item.get("discovered_automatically", False)),
        repository_url=_optional_string(
            item.get("repository_url"), f"{source_id}.repository_url"
        ),
        stars=_optional_non_negative_int(item.get("stars"), f"{source_id}.stars"),
        repository_created_at=_optional_string(
            item.get("repository_created_at"), f"{source_id}.repository_created_at"
        ),
        repository_updated_at=_optional_string(
            item.get("repository_updated_at"), f"{source_id}.repository_updated_at"
        ),
        repository_pushed_at=_optional_string(
            item.get("repository_pushed_at"), f"{source_id}.repository_pushed_at"
        ),
        default_branch=_optional_string(
            item.get("default_branch"), f"{source_id}.default_branch"
        ),
        package_name=_optional_string(item.get("package_name"), f"{source_id}.package_name"),
        package_version=_optional_string(
            item.get("package_version"), f"{source_id}.package_version"
        ),
        release_date=_optional_string(item.get("release_date"), f"{source_id}.release_date"),
        homepage=_optional_string(item.get("homepage"), f"{source_id}.homepage"),
        project_url=_optional_string(item.get("project_url"), f"{source_id}.project_url"),
        author=_optional_string(item.get("author"), f"{source_id}.author"),
        summary=_optional_string(item.get("summary"), f"{source_id}.summary"),
        keywords=_optional_string(item.get("keywords"), f"{source_id}.keywords"),
        source_archive=_optional_string(
            item.get("source_archive"), f"{source_id}.source_archive"
        ),
        download_url=_optional_string(item.get("download_url"), f"{source_id}.download_url"),
        archive_sha256=_optional_string(
            item.get("archive_sha256"), f"{source_id}.archive_sha256"
        ),
    )


def _discover_automatic_import_sources(
    project_root: Path,
    imports_directory: Path,
    settings: Mapping[str, Any],
    configured_sources: tuple[CorpusSource, ...],
) -> tuple[CorpusSource, ...]:
    """Register first-level approved repositories and ZIPs from an import directory."""

    approval = _required_string(
        settings.get("approval"),
        "corpus_collection.automatic_imports.approval",
    )
    default_license = _optional_string(
        settings.get("default_license"),
        "corpus_collection.automatic_imports.default_license",
    )
    metadata_file = _required_string(
        settings.get("metadata_file", DEFAULT_IMPORT_METADATA_FILE),
        "corpus_collection.automatic_imports.metadata_file",
    )
    if Path(metadata_file).name != metadata_file:
        raise CorpusCollectionError(
            "corpus_collection.automatic_imports.metadata_file must be a filename."
        )
    default_include = _string_tuple(
        settings.get("include", ["**/*.py"]),
        "corpus_collection.automatic_imports.include",
    )
    default_exclude = _string_tuple(
        settings.get("exclude", []),
        "corpus_collection.automatic_imports.exclude",
    )
    discover_zip_archives = bool(settings.get("discover_zip_archives", True))
    if not imports_directory.exists():
        return ()
    if not imports_directory.is_dir():
        raise CorpusCollectionError(
            f"Automatic imports path is not a directory: {imports_directory}"
        )

    configured_locations = {
        _resolve(project_root, source.location)
        for source in configured_sources
        if source.source_type in {"local", "git", "zip"}
    }
    used_ids = {source.source_id for source in configured_sources}
    discovered: list[CorpusSource] = []
    for child in sorted(imports_directory.iterdir(), key=lambda path: path.name.casefold()):
        if child.is_symlink() or child.name.startswith("."):
            continue
        if child.is_dir():
            source_type = "git" if (child / ".git").exists() else "local"
            metadata_path = child / metadata_file
        elif discover_zip_archives and child.is_file() and child.suffix.casefold() == ".zip":
            source_type = "zip"
            metadata_path = child.with_name(f"{child.name}{metadata_file}")
        else:
            continue
        if child.resolve() in configured_locations:
            continue
        metadata = _load_import_metadata(metadata_path)
        source_id = _automatic_source_id(
            metadata.get("id", child.stem if source_type == "zip" else child.name),
            used_ids,
        )
        location = _portable_location(project_root, child)
        source = _load_source(
            {
                "id": source_id,
                "type": source_type,
                "location": location,
                "license": metadata.get("license", default_license),
                "approval": metadata.get("approval", approval),
                "revision": metadata.get("revision"),
                "include": metadata.get("include", default_include),
                "exclude": metadata.get("exclude", default_exclude),
                "discovered_automatically": True,
            }
        )
        used_ids.add(source.source_id)
        discovered.append(source)
    return tuple(discovered)


def _load_import_metadata(path: Path) -> dict[str, Any]:
    if not path.is_file():
        return {}
    try:
        value = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    except (OSError, UnicodeDecodeError, yaml.YAMLError) as exc:
        raise CorpusCollectionError(f"Invalid automatic import metadata {path}: {exc}") from exc
    if not isinstance(value, dict):
        raise CorpusCollectionError(
            f"Automatic import metadata must be a YAML mapping: {path}"
        )
    allowed = {"id", "license", "approval", "revision", "include", "exclude"}
    unknown = sorted(set(value) - allowed)
    if unknown:
        raise CorpusCollectionError(
            f"Unknown automatic import metadata fields in {path}: {', '.join(unknown)}"
        )
    return value


def _automatic_source_id(value: object, used_ids: set[str]) -> str:
    name = _required_string(value, "automatic import source id")
    slug = re.sub(r"[^A-Za-z0-9_.-]+", "-", name).strip(".-_").lower()
    if not slug:
        slug = hashlib.sha256(name.encode("utf-8")).hexdigest()[:12]
    base = f"import-{slug}"
    candidate = base
    if candidate in used_ids:
        suffix = hashlib.sha256(name.encode("utf-8")).hexdigest()[:8]
        candidate = f"{base}-{suffix}"
    counter = 2
    while candidate in used_ids:
        candidate = f"{base}-{counter}"
        counter += 1
    return candidate


def _portable_location(project_root: Path, path: Path) -> str:
    try:
        return path.resolve().relative_to(project_root.resolve()).as_posix()
    except ValueError:
        return str(path.resolve())


def _validate_config(config: CorpusCollectorConfig) -> None:
    if config.minimum_file_bytes < 0:
        raise CorpusCollectionError("corpus_collection.minimum_file_bytes must be non-negative.")
    if config.maximum_file_bytes <= config.minimum_file_bytes:
        raise CorpusCollectionError(
            "corpus_collection.maximum_file_bytes must exceed minimum_file_bytes."
        )
    if config.git_timeout_seconds <= 0:
        raise CorpusCollectionError("corpus_collection.git_timeout_seconds must be positive.")
    if not config.allowed_extensions:
        raise CorpusCollectionError("corpus_collection.allowed_extensions must not be empty.")
    for metadata_path in (config.provenance_manifest, config.report_path):
        try:
            metadata_path.resolve().relative_to(config.output_directory.resolve())
        except ValueError as exc:
            raise CorpusCollectionError(
                f"Collector metadata must be stored under {config.output_directory}: "
                f"{metadata_path}"
            ) from exc


def _source_path_selected(source: CorpusSource, path: PurePosixPath) -> bool:
    value = path.as_posix()
    return _matches_any(value, source.include) and not _matches_any(value, source.exclude)


def _matches_any(path: str, patterns: Iterable[str]) -> bool:
    return any(
        fnmatch.fnmatch(path, pattern)
        or PurePosixPath(path).match(pattern)
        or (pattern.startswith("**/") and fnmatch.fnmatch(path, pattern[3:]))
        for pattern in patterns
    )


def _is_supported_extension(path: str | PurePosixPath, extensions: Iterable[str]) -> bool:
    suffix = PurePosixPath(str(path)).suffix.casefold()
    return suffix in {extension.casefold() for extension in extensions}


def _is_python_path(path: str | PurePosixPath) -> bool:
    return PurePosixPath(str(path)).suffix.casefold() == ".py"


def _content_type(path: str | PurePosixPath) -> str:
    return "python_code" if _is_python_path(path) else "technical_text"


def _content_language(path: str | PurePosixPath) -> str:
    suffix = PurePosixPath(str(path)).suffix.casefold()
    if suffix == ".py":
        return "Python"
    if suffix == ".md":
        return "Markdown"
    if suffix == ".rst":
        return "reStructuredText"
    return "Text"


def _is_generated(config: CorpusCollectorConfig, path: PurePosixPath) -> bool:
    value = path.as_posix().casefold()
    name = path.name.casefold()
    return any(
        fnmatch.fnmatch(name, pattern.casefold())
        or fnmatch.fnmatch(value, pattern.casefold())
        for pattern in config.generated_file_patterns
    )


def _has_ignored_part(config: CorpusCollectorConfig, path: PurePosixPath) -> bool:
    ignored = tuple(item.casefold() for item in config.ignored_directories)
    return any(
        fnmatch.fnmatch(part.casefold(), pattern)
        for part in path.parts[:-1]
        for pattern in ignored
    )


def _unsafe_archive_path(path: PurePosixPath) -> bool:
    return (
        path.is_absolute()
        or not path.parts
        or any(part in {"", ".", ".."} for part in path.parts)
    )


def _safe_destination(root: Path, relative: PurePosixPath) -> Path:
    if _unsafe_archive_path(relative):
        raise CorpusCollectionError(f"Unsafe corpus destination path: {relative}")
    destination = root.joinpath(*relative.parts).resolve()
    try:
        destination.relative_to(root.resolve())
    except ValueError as exc:
        raise CorpusCollectionError(
            f"Corpus destination escapes output directory: {relative}"
        ) from exc
    return destination


def _is_within(path: Path, directory: Path) -> bool:
    try:
        path.resolve().relative_to(directory.resolve())
    except ValueError:
        return False
    return True


def _reject(statistics: SourceStatistics, reason: str) -> None:
    statistics.files_rejected += 1
    statistics.rejection_reasons[reason] += 1


def _resolve(project_root: Path, value: object) -> Path:
    text = _required_string(value, "path")
    candidate = Path(text).expanduser()
    return candidate.resolve() if candidate.is_absolute() else (project_root / candidate).resolve()


def _mapping(value: object, label: str) -> dict[str, Any]:
    if not isinstance(value, dict):
        raise CorpusCollectionError(f"{label} must be a mapping.")
    return value


def _required_string(value: object, label: str) -> str:
    if not isinstance(value, str) or not value.strip():
        raise CorpusCollectionError(f"{label} must be a non-empty string.")
    return value.strip()


def _optional_string(value: object, label: str) -> str | None:
    if value is None:
        return None
    if not isinstance(value, str):
        raise CorpusCollectionError(f"{label} must be a string or null.")
    return value.strip() or None


def _optional_non_negative_int(value: object, label: str) -> int | None:
    if value is None:
        return None
    if not isinstance(value, int) or isinstance(value, bool) or value < 0:
        raise CorpusCollectionError(f"{label} must be a non-negative integer or null.")
    return value


def _string_tuple(value: object, label: str) -> tuple[str, ...]:
    if not isinstance(value, (list, tuple)) or not all(
        isinstance(item, str) and item.strip() for item in value
    ):
        raise CorpusCollectionError(f"{label} must be a list of non-empty strings.")
    return tuple(item.strip() for item in value)


def _extension_tuple(value: object, label: str) -> tuple[str, ...]:
    extensions = _string_tuple(value, label)
    normalized: list[str] = []
    for extension in extensions:
        item = extension.casefold()
        if not item.startswith(".") or len(item) < 2:
            raise CorpusCollectionError(f"{label} entries must look like '.py'.")
        normalized.append(item)
    return tuple(dict.fromkeys(normalized))


def _bytes_hash(content: bytes) -> str:
    return hashlib.sha256(content).hexdigest()


def _file_hash(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as file:
        for chunk in iter(lambda: file.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _timestamp() -> str:
    return datetime.now(UTC).isoformat()


__all__ = [
    "CollectionResult",
    "CorpusCollectionError",
    "CorpusCollectorConfig",
    "CorpusSource",
    "collect_python_corpus",
    "configure_collector_logging",
    "load_corpus_collector_config",
    "run_corpus_collector_cli",
]
