"""Cleaning and normalization for Corpus V2 documents."""

from __future__ import annotations

import re
from dataclasses import dataclass

from genpy_llm.corpus_v2.manifest import CleanDocument, CollectedDocument, content_hash


@dataclass(frozen=True)
class CleanSettings:
    """Configurable document cleaning thresholds."""

    minimum_file_bytes: int = 80
    maximum_file_bytes: int = 2_000_000
    normalize_tabs: bool = True
    tab_width: int = 4


@dataclass(frozen=True)
class CleanResult:
    """Result of cleaning one collected document."""

    document: CleanDocument | None
    rejection_reason: str | None = None


GENERATED_NAME_PATTERNS = (
    "_pb2.py",
    "_pb2_grpc.py",
    ".lock",
    "package-lock.json",
    "poetry.lock",
    "pdm.lock",
)
GENERATED_MARKERS = (
    "@generated",
    "auto-generated",
    "autogenerated",
    "automatically generated",
    "generated by",
    "do not edit",
)


def clean_document(document: CollectedDocument, settings: CleanSettings) -> CleanResult:
    """Normalize text and reject corrupted or low-signal files."""

    size = len(document.content)
    if size < settings.minimum_file_bytes:
        return CleanResult(None, "too_short")
    if size > settings.maximum_file_bytes:
        return CleanResult(None, "too_large")
    lower_path = document.relative_path.casefold()
    if any(pattern in lower_path for pattern in GENERATED_NAME_PATTERNS):
        return CleanResult(None, "generated_file")
    try:
        text = document.content.decode("utf-8-sig")
    except UnicodeDecodeError:
        return CleanResult(None, "invalid_utf8")
    text = normalize_text(text, settings)
    if not text.strip():
        return CleanResult(None, "empty_file")
    header = "\n".join(text.splitlines()[:10]).casefold()
    if any(marker in header for marker in GENERATED_MARKERS):
        return CleanResult(None, "generated_file")
    if _is_minified(text):
        return CleanResult(None, "minified_file")
    encoded = text.encode("utf-8")
    return CleanResult(
        CleanDocument(
            source=document.source,
            path=document.path,
            relative_path=document.relative_path,
            text=text,
            content_type=document.content_type,
            sha256=content_hash(encoded),
            byte_count=len(encoded),
            line_count=len(text.splitlines()),
        )
    )


def normalize_text(text: str, settings: CleanSettings) -> str:
    """Normalize line endings, tabs, control characters, and repeated blank lines."""

    text = text.replace("\r\n", "\n").replace("\r", "\n").rstrip("\x00")
    text = "".join(char for char in text if char in {"\n", "\t"} or ord(char) >= 32)
    if settings.normalize_tabs:
        text = text.expandtabs(settings.tab_width)
    text = "\n".join(line.rstrip() for line in text.splitlines())
    text = re.sub(r"\n{4,}", "\n\n\n", text)
    return text.strip() + "\n"


def _is_minified(text: str) -> bool:
    lines = text.splitlines()
    if not lines:
        return False
    longest = max((len(line) for line in lines), default=0)
    average = sum(len(line) for line in lines) / len(lines)
    return longest > 5_000 or (len(lines) <= 3 and average > 1_000)


__all__ = [
    "CleanResult",
    "CleanSettings",
    "clean_document",
    "normalize_text",
]
